"""
Tools module for LangGraph agent tools.

This module provides various tool nodes that agents can use
for database, vector store, file operations, and more.
"""

from .database import (
    DatabaseToolNode,
    GetUserTool,
    GetProjectTool,
    GetDecisionsTool,
    CreateDecisionTool,
    GetArtifactsTool,
    CreateArtifactTool,
    GetBranchesTool,
    CreateBranchTool,
    AddCommentTool,
    UpdateProjectTool,
)

from .vector import (
    VectorStoreToolNode,
    SearchDecisionsTool,
    IndexDecisionTool,
    SearchArtifactsTool,
    IndexArtifactTool,
    GetRAGContextTool,
    FindSimilarDecisionsTool,
    DeleteFromIndexTool,
    create_vector_tools,
)

from .file import (
    FileOperationToolNode,
    ReadFileTool,
    WriteFileTool,
    ListDirectoryTool,
    GlobSearchTool,
    GetFileInfoTool,
    DeleteFileTool,
    CopyFileTool,
    MoveFileTool,
    CreateDirectoryTool,
    create_file_tools,
)

from .git import (
    GitToolNode,
    CloneRepoTool,
    InitRepoTool,
    ListBranchesTool,
    CreateBranchTool,
    CheckoutBranchTool,
    GetCommitLogTool,
    GetDiffTool,
    CommitChangesTool,
    PushChangesTool,
    PullChangesTool,
    GitStatusTool,
    create_git_tools,
)

from .code_analysis import (
    CodeAnalysisToolNode,
    DetectLanguageTool,
    ParseASTTool,
    TypeAwareAnalysisTool,
    DynamicHeuristicAnalysisTool,
    InferArchitectureTool,
    GenerateComponentInventoryTool,
    GenerateC4ModelTool,
    RenderC4MermaidTool,
    ArchitectureAnnotationInterfaceTool,
    ExtractFunctionsTool,
    ExtractClassesTool,
    ExtractImportsTool,
    BuildDependencyGraphTool,
    ClassifyFileImpactTool,
    TraceDownstreamDependenciesTool,
    DetectBreakingChangesTool,
    AnalyzeTypeSystemChangesTool,
    AssessTestImpactTool,
    AssessRiskLevelTool,
    IdentifyAffectedFeaturesTool,
    GenerateChangeProcedureTool,
    GenerateGitWorkflowTool,
    GenerateCommitSequenceTool,
    GenerateRollbackProcedureTool,
    GenerateFeatureFlagStrategyTool,
    GenerateMultiPhaseRolloutPlanTool,
    GenerateDatabaseMigrationStrategyTool,
    GetCodeMetricsTool,
    GenerateCodebaseMetricsTool,
    ScanDirectoryTool,
    create_code_analysis_tools,
)

from .errors import (
    ToolError,
    ToolErrorSeverity,
    ToolErrorCategory,
    ToolErrorCode,
    ToolExecutionResult,
    ErrorRecoveryStrategy,
    ErrorRecoveryRule,
    ToolErrorHandler,
    ToolExecutor,
    create_error_handler,
    create_tool_executor,
    with_error_handling,
)

from .registry import (
    ToolRegistry,
    ToolStatus,
    ToolCategory,
    ToolMetadata,
    ToolSchema,
    RegisteredTool,
    ToolFilter,
    get_registry,
    register_tool,
    register_decorator,
    list_tools,
    list_tool_instances,
    get_tool,
    get_tool_by_name,
    search_tools,
)

from .validation import (
    ToolValidator,
    ValidationResult,
    ValidationIssue,
    ValidationSeverity,
    ValidationCategory,
    SchemaDefinition,
    create_validator,
    validate_tool_input,
    validate_tool_output,
    generate_schema_from_model,
)

from .documentation import (
    ToolDocumentationGenerator,
    ToolDoc,
    ParameterDoc,
    ExampleDoc,
    ToolStatus as DocToolStatus,
    DocFormat,
    create_documentation_generator,
    create_auto_documenter,
    generate_database_tools_docs,
    generate_vector_tools_docs,
)

from .versioning import (
    ToolVersionManager,
    CompatibilityChecker,
    VersionInfo,
    BreakingChange,
    CompatibilityReport,
    ToolVersion,
    VersionChangeType,
    CompatibilityLevel,
    BreakingChangeType,
    DeprecationStatus,
    create_version_manager,
    create_compatibility_checker,
    parse_version,
    compare_versions,
)

__all__ = [
    # Database tools
    "DatabaseToolNode",
    "GetUserTool",
    "GetProjectTool",
    "GetDecisionsTool",
    "CreateDecisionTool",
    "GetArtifactsTool",
    "CreateArtifactTool",
    "GetBranchesTool",
    "CreateBranchTool",
    "AddCommentTool",
    "UpdateProjectTool",
    # Vector store tools
    "VectorStoreToolNode",
    "SearchDecisionsTool",
    "IndexDecisionTool",
    "SearchArtifactsTool",
    "IndexArtifactTool",
    "GetRAGContextTool",
    "FindSimilarDecisionsTool",
    "DeleteFromIndexTool",
    "create_vector_tools",
    # File operation tools
    "FileOperationToolNode",
    "ReadFileTool",
    "WriteFileTool",
    "ListDirectoryTool",
    "GlobSearchTool",
    "GetFileInfoTool",
    "DeleteFileTool",
    "CopyFileTool",
    "MoveFileTool",
    "CreateDirectoryTool",
    "create_file_tools",
    # Git operation tools
    "GitToolNode",
    "CloneRepoTool",
    "InitRepoTool",
    "ListBranchesTool",
    "CreateBranchTool",
    "CheckoutBranchTool",
    "GetCommitLogTool",
    "GetDiffTool",
    "CommitChangesTool",
    "PushChangesTool",
    "PullChangesTool",
    "GitStatusTool",
    "create_git_tools",
    # Code analysis tools
    "CodeAnalysisToolNode",
    "DetectLanguageTool",
    "ParseASTTool",
    "TypeAwareAnalysisTool",
    "DynamicHeuristicAnalysisTool",
    "InferArchitectureTool",
    "GenerateComponentInventoryTool",
    "GenerateC4ModelTool",
    "RenderC4MermaidTool",
    "ArchitectureAnnotationInterfaceTool",
    "ExtractFunctionsTool",
    "ExtractClassesTool",
    "ExtractImportsTool",
    "BuildDependencyGraphTool",
    "ClassifyFileImpactTool",
    "TraceDownstreamDependenciesTool",
    "DetectBreakingChangesTool",
    "AnalyzeTypeSystemChangesTool",
    "AssessTestImpactTool",
    "AssessRiskLevelTool",
    "IdentifyAffectedFeaturesTool",
    "GenerateChangeProcedureTool",
    "GenerateGitWorkflowTool",
    "GenerateCommitSequenceTool",
    "GenerateRollbackProcedureTool",
    "GenerateFeatureFlagStrategyTool",
    "GenerateMultiPhaseRolloutPlanTool",
    "GenerateDatabaseMigrationStrategyTool",
    "GetCodeMetricsTool",
    "GenerateCodebaseMetricsTool",
    "ScanDirectoryTool",
    "create_code_analysis_tools",
    # Error handling
    "ToolError",
    "ToolErrorSeverity",
    "ToolErrorCategory",
    "ToolErrorCode",
    "ToolExecutionResult",
    "ErrorRecoveryStrategy",
    "ErrorRecoveryRule",
    "ToolErrorHandler",
    "ToolExecutor",
    "create_error_handler",
    "create_tool_executor",
    "with_error_handling",
    # Tool registry
    "ToolRegistry",
    "ToolStatus",
    "ToolCategory",
    "ToolMetadata",
    "ToolSchema",
    "RegisteredTool",
    "ToolFilter",
    "get_registry",
    "register_tool",
    "register_decorator",
    "list_tools",
    "list_tool_instances",
    "get_tool",
    "get_tool_by_name",
    "search_tools",
    # Validation
    "ToolValidator",
    "ValidationResult",
    "ValidationIssue",
    "ValidationSeverity",
    "ValidationCategory",
    "SchemaDefinition",
    "create_validator",
    "validate_tool_input",
    "validate_tool_output",
    "generate_schema_from_model",
    # Documentation
    "ToolDocumentationGenerator",
    "ToolDoc",
    "ParameterDoc",
    "ExampleDoc",
    "ToolStatus",
    "DocFormat",
    "create_documentation_generator",
    "create_auto_documenter",
    "generate_database_tools_docs",
    "generate_vector_tools_docs",
    # Versioning
    "ToolVersionManager",
    "CompatibilityChecker",
    "VersionInfo",
    "BreakingChange",
    "CompatibilityReport",
    "ToolVersion",
    "VersionChangeType",
    "CompatibilityLevel",
    "BreakingChangeType",
    "DeprecationStatus",
    "create_version_manager",
    "create_compatibility_checker",
    "parse_version",
    "compare_versions",
]
