"""
Tools module for LangGraph agent tools.

This module provides various tool nodes that agents can use
for database, vector store, file operations, and more.
"""

from .database import (
    DatabaseToolNode,
    GetUserTool,
    GetProjectTool,
    GetDecisionsTool,
    CreateDecisionTool,
    GetArtifactsTool,
    CreateArtifactTool,
    GetBranchesTool,
    CreateBranchTool,
    AddCommentTool,
    UpdateProjectTool,
)

from .vector import (
    VectorStoreToolNode,
    SearchDecisionsTool,
    IndexDecisionTool,
    SearchArtifactsTool,
    IndexArtifactTool,
    GetRAGContextTool,
    FindSimilarDecisionsTool,
    DeleteFromIndexTool,
    create_vector_tools,
)

from .file import (
    FileOperationToolNode,
    ReadFileTool,
    WriteFileTool,
    ListDirectoryTool,
    GlobSearchTool,
    GetFileInfoTool,
    DeleteFileTool,
    CopyFileTool,
    MoveFileTool,
    CreateDirectoryTool,
    create_file_tools,
)

from .git import (
    GitToolNode,
    CloneRepoTool,
    InitRepoTool,
    ListBranchesTool,
    CreateBranchTool,
    CheckoutBranchTool,
    GetCommitLogTool,
    GetDiffTool,
    CommitChangesTool,
    PushChangesTool,
    PullChangesTool,
    GitStatusTool,
    create_git_tools,
)

from .code_analysis import (
    CodeAnalysisToolNode,
    DetectLanguageTool,
    ParseASTTool,
    ExtractFunctionsTool,
    ExtractClassesTool,
    ExtractImportsTool,
    GetCodeMetricsTool,
    ScanDirectoryTool,
    create_code_analysis_tools,
)

from .errors import (
    ToolError,
    ToolErrorSeverity,
    ToolErrorCategory,
    ToolErrorCode,
    ToolExecutionResult,
    ErrorRecoveryStrategy,
    ErrorRecoveryRule,
    ToolErrorHandler,
    ToolExecutor,
    create_error_handler,
    create_tool_executor,
    with_error_handling,
)

from .registry import (
    ToolRegistry,
    ToolStatus,
    ToolCategory,
    ToolMetadata,
    ToolSchema,
    RegisteredTool,
    ToolFilter,
    get_registry,
    register_tool,
    register_decorator,
    list_tools,
    list_tool_instances,
    get_tool,
    get_tool_by_name,
    search_tools,
)

__all__ = [
    # Database tools
    "DatabaseToolNode",
    "GetUserTool",
    "GetProjectTool",
    "GetDecisionsTool",
    "CreateDecisionTool",
    "GetArtifactsTool",
    "CreateArtifactTool",
    "GetBranchesTool",
    "CreateBranchTool",
    "AddCommentTool",
    "UpdateProjectTool",
    # Vector store tools
    "VectorStoreToolNode",
    "SearchDecisionsTool",
    "IndexDecisionTool",
    "SearchArtifactsTool",
    "IndexArtifactTool",
    "GetRAGContextTool",
    "FindSimilarDecisionsTool",
    "DeleteFromIndexTool",
    "create_vector_tools",
    # File operation tools
    "FileOperationToolNode",
    "ReadFileTool",
    "WriteFileTool",
    "ListDirectoryTool",
    "GlobSearchTool",
    "GetFileInfoTool",
    "DeleteFileTool",
    "CopyFileTool",
    "MoveFileTool",
    "CreateDirectoryTool",
    "create_file_tools",
    # Git operation tools
    "GitToolNode",
    "CloneRepoTool",
    "InitRepoTool",
    "ListBranchesTool",
    "CreateBranchTool",
    "CheckoutBranchTool",
    "GetCommitLogTool",
    "GetDiffTool",
    "CommitChangesTool",
    "PushChangesTool",
    "PullChangesTool",
    "GitStatusTool",
    "create_git_tools",
    # Code analysis tools
    "CodeAnalysisToolNode",
    "DetectLanguageTool",
    "ParseASTTool",
    "ExtractFunctionsTool",
    "ExtractClassesTool",
    "ExtractImportsTool",
    "GetCodeMetricsTool",
    "ScanDirectoryTool",
    "create_code_analysis_tools",
    # Error handling
    "ToolError",
    "ToolErrorSeverity",
    "ToolErrorCategory",
    "ToolErrorCode",
    "ToolExecutionResult",
    "ErrorRecoveryStrategy",
    "ErrorRecoveryRule",
    "ToolErrorHandler",
    "ToolExecutor",
    "create_error_handler",
    "create_tool_executor",
    "with_error_handling",
    # Tool registry
    "ToolRegistry",
    "ToolStatus",
    "ToolCategory",
    "ToolMetadata",
    "ToolSchema",
    "RegisteredTool",
    "ToolFilter",
    "get_registry",
    "register_tool",
    "register_decorator",
    "list_tools",
    "list_tool_instances",
    "get_tool",
    "get_tool_by_name",
    "search_tools",
]
